import Head from "next/head";
import RadarSection from "../sections/radar-section/RadarSection";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Radar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <RadarSection />
      </section>
    </div>
  );
}
