import Head from "next/head";
import CarouselSection from "../sections/carousel-section/CarouselSection";
import RadarSection from "../sections/radar-section/RadarSection";
import ServicesSection from "../sections/services-section/ServicesSection";
import TechnologySection from "../sections/technology-section/TechnologySection";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.MainWrapper}>
      <Head>
        <title>Radar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.App}>
        <RadarSection />
        <ServicesSection />
        <TechnologySection />
        <CarouselSection />
      </section>
    </div>
  );
}
